### PR TITLE
GUI.py: Resize image adequately

### LINKED ISSUE #227: Make GUI better.
Two things
1. The whole picture should fit the frame.
2. As a whole UI should be made to look better. Maybe use something other than tkinter before it's to late.

### PR DESCRIPTION
**Pull request by RyuujenJakka**
This lets the user preview the whole wallpaper

Fixes #227

### CODE REVIEW

**Comment by nkprince007** [comment]
:stuck_out_tongue_closed_eyes: remove partially closes thing..

**Comment by RyuujenJakka** [comment]
@nkprince007 removed it. :stuck_out_tongue_winking_eye:

**Comment by abhsag24** [comment]
@RyuujenJakka does this not fix the issue? is there still some problem?

**Comment by RyuujenJakka** [comment]
Ok. I will change it to Fixes.

**Comment by RyuujenJakka** [comment]
Done.

**Comment by abhsag24** [comment]
@RyuujenJakka can you post a screenshot of it working? maybe a with it and without it kind of thing?

**Comment by RyuujenJakka** [comment]
Yeah, Sure.Before:
 Before 
After:
After
Before:
Before
After:
Before

**Comment by abhsag24** [comment]
@RyuujenJakka  awesome @nkprince007  why did we resize like that earlier in the first place?

**Pull request merged**
