### PR TITLE
Updated README.md

### LINKED ISSUE #213: Readme: Run: UIP.py --> UIP

### PR DESCRIPTION
**Pull request by hackrush01**
Looks like I am gonna be on "README duty" for a while now!

Fixes #213

### CODE REVIEW

**Comment by nkprince007** [comment]
This looks good enough. Merging it @abhsag24

**Comment by abhsag24** [comment]
@hackrush01 see the HOW TO CONTRIBUTE section in the Readme to now what is the standard commit structure for this repository

**Comment by hackrush01** [comment]
Done.

-Regards
-Amit Tulshyan

**Comment by abhsag24** [comment]
@hackrush01 the commit shortlog is still not updated, Updated Readme is not a good commit message

**Pull request closed without merging**
