### PR TITLE
Added Status Icon (minimzed to system tray) in Linux

### PR DESCRIPTION
**Pull request by Aniq55**

### CODE REVIEW

**Comment by abhsag24** [comment]
Hi thank you for your Patch make sure you have the right commit structure that is 
```
tag: Shortlog

body
Fixes <issue number/url>
```
Also please upload a screenshot if you have made changes to the gui.

**Comment by nkprince007** [comment]
https://www.blog.pythonlibrary.org/2013/07/12/wxpython-how-to-minimize-to-system-tray/

This might help us with the windows edition of system tray.

**Comment by nkprince007** [comment]
And this one for macOS

https://github.com/jaredks/rumps

**Comment by abhsag24** [comment]
merging :D

**Comment by abhsag24** [comment]
@Aniq55 can u help in providing windows support too?

**Comment by nkprince007** [comment]
I'll update the OS X version ;) @abhsag24

**Comment by Aniq55** [comment]
Finally. :) Sure @abhsag24 once I set up github on windows.

**Pull request merged**
