### PR TITLE
Setup.py : Removed non-descriptive comments

### LINKED ISSUE #129: Setup.py: Add comments
Add comments to the fields `license` and `url` in setup.py.

### PR DESCRIPTION
**Pull request by lohani2280**
removed all comments that were  non-descriptive and just take up lines ,except for entry_points.    
            
Fixes  #129

### CODE REVIEW

**Comment by abhsag24** [comment]
@lohani2280 can you do `sudo pip3 install test-requirements.txt` and then run coala over your code and ammend your commit ? you seem to have linting issues

**Comment by lohani2280** [comment]
Yeah sure , i'll try to do it.

**Comment by lohani2280** [comment]
@abhsag24 Sorry , but can u plz elaborate me what does it mean to "run coala over your code".

**Comment by nkprince007** [comment]
@lohani2280 `coala` is a command line tool used to lint and fix code for multiple languages. It also supports python. You could get started with coala [here](https://coala.io/)

**Pull request closed without merging**
