### PR TITLE
Added screenshot to the Readme (Issue #51)

### PR DESCRIPTION
**Pull request by Aniq55**
Created an examples folder with the screenshot .png file and used relative path to display the screenshot in README.md

### CODE REVIEW

**Comment by nkprince007** [comment]
Nice work with the wallpaper. 👍  

But I rather suppose, since we support multiple platforms 
- linux 
- win32(Windows)
- darwin(macOS)

It's gonna be better if we were to stack and show all three of them in one picture. ❤️

**Comment by Aniq55** [comment]
It's highly unlikely for one guy to do for all three, so this change should
be merged for now and similar changes will be done for Windows and Mac by
adding images in the examples folder and then changing the readme file
accordingly.

**Comment by abhsag24** [comment]
can we do a programatic type thing in README where all files in the example folder are displayed?

**Comment by abhsag24** [comment]
i think we should merge for now @nkprince007 can you open an issue for wallpapers from all desktop environments? i can add windows and you can add mac i guess?

**Comment by abhsag24** [comment]
i'll merge it as soon as @nkprince007 gives the go ahead :P

**Comment by abhsag24** [comment]
@Aniq55 @nkprince007  merging since i can't wait to see the pic in README anymore :P also @Aniq55  is right a person can't have all 3 OS' right :P ?

**Pull request merged**
