### PR TITLE
GUI: Arranged Set Wallpaper and Flush button side by side

### PR DESCRIPTION
**Pull request by Aniq55**
Fixes: #287

### CODE REVIEW

**Comment by abhsag24** [comment]
Hi thank you for your Patch make sure you have the right commit structure that is 
```
tag: Shortlog

body
Fixes <issue number/url>
```

**Comment by abhsag24** [comment]
@Aniq55 can we have a screenshot here of how it looks?

**Comment by nemaniarjun** [comment]
@Aniq55 They dont need to be 2 commits, squash them into one. 
Hint: You should use `git commit --amend` if you are just changing the last commit.

**Comment by Aniq55** [comment]
Will squash them, once all the checks are okay. @nemaniarjun

**Comment by Aniq55** [comment]
screenshot from 2016-12-28 14-59-56
@abhsag24

**Comment by Aniq55** [comment]
I've checked all the indentation stuff, but still Travis is giving error @abhsag24 @nemaniarjun

**Comment by abhsag24** [comment]
@Aniq55 do `pip install -r test-requirements.txt` and then do `coala`

**Comment by Aniq55** [comment]
I have to update to python 3.5 first. Then it should work. Got it! @abhsag24

**Comment by abhsag24** [comment]
@Aniq55 yes i assumed you were using a virtual environment

**Comment by abhsag24** [comment]
@Aniq55 can you show us how it looks with the blur bar added?

**Comment by abhsag24** [comment]
@Aniq55 also please squash all your commits

**Comment by Aniq55** [comment]
screenshot from 2016-12-28 18-13-44

@abhsag24

**Comment by abhsag24** [comment]
awesome now just need to squash all your commits :P

**Pull request merged**
