### PR TITLE
generalTab.py :  flush button removed

### PR DESCRIPTION
**Pull request by jayantsaraf**
flush button is removed from generalTab.py

Fixes : NIT-dgp/UIP #350

### CODE REVIEW

**Comment by abhsag24** [comment]
Hi thank you for your Patch make sure you have the right commit structure that is 
```
tag: Shortlog

body
Fixes <issue number/url>
```
Also please upload a screenshot if you have made changes to the gui.

**Comment by abhsag24** [comment]
@jayantsaraf you have merge conflict, it means your local files are not upto date with our master branch. please correct your commits, and solve these conflicts(probably the reason why all ticks fail)

**Comment by jayantsaraf** [comment]
can you please guide me how to do this?

**Comment by abhsag24** [comment]
@jayantsaraf gp through this: https://www.atlassian.com/git/tutorials/rewriting-history

**Comment by nkprince007** [comment]
Closing due to inactivity and the presence of a new PR #368

**Pull request closed without merging**
