### PR TITLE
remove comments 

### PR DESCRIPTION
**Pull request by jayantsaraf**

### CODE REVIEW

**Comment by abhsag24** [comment]
Hi thank you for your Patch make sure you have the right commit structure that is 
```
tag: Shortlog

body
Fixes <issue number/url>
```
Also please upload a screenshot if you have made changes to the gui.

**Comment by nkprince007** [comment]
Was there an issue for this?

**Comment by abhsag24** [comment]
please folllow the proper commit structure @jayantsaraf

**Comment by jayantsaraf** [comment]
@abhsag24  can you please tell me the proper commit structure. i am unable to understand it from the syntax

**Comment by nkprince007** [comment]
Closing due to the presence of a newer PR #368

**Pull request closed without merging**
