### PR TITLE
Remove-Comment-#129

### PR DESCRIPTION
**Pull request by lohani2280**
Removed all  comments except for entry_points.

### CODE REVIEW

**Comment by nkprince007** [comment]
Why've you removed the comments? :scream:
They add the readability to the code.

>Programs are written for humans to read, and only incidentally for machines to execute.

**Comment by abhsag24** [comment]
@nkprince007 that was the issue. Those comments provide no help they were the generic comments that came with `setup.py`

**Comment by abhsag24** [comment]
@lohani2280 you do have a merge conflict which you've got to resolve

**Comment by abhsag24** [comment]
also the commit structure isn't how we want in the repo, please see the `HOW TO CONTRIBUTE` section in the `Readme` file

**Pull request closed without merging**
