### PR TITLE
Add utils folder, differentiate, setup-utils, and regular utils

### LINKED ISSUE #224: Add utils folder, differentiate, setup-utils, and regular utils
right now setup requires functions from `utils` but breaks everytime we connect it to the main code. It'd be best if we could differentiate utils into `setup-utils` and `uip-utils`

### PR DESCRIPTION
**Pull request by hackrush01**
Made a new folder `utils` in uiplib, and added the setup required methods in `setupUtils.py` and others are kept unchanged in `utils.py` only.

Fixes #224

### CODE REVIEW

**Comment by abhsag24** [comment]
@hackrush01 can you rebase away the previous commit that doesn't belong to this PR

**Comment by hackrush01** [comment]
Is this what you wanted?

**Comment by abhsag24** [comment]
@hackrush01 the last commit, yes pretty much :D

**Comment by hackrush01** [comment]
I have no idea about rebasing such things.

**Comment by abhsag24** [comment]
i will review in detail a little later but from just looking at it. It seems good. Can you please fix the commit message though? just do `git commit --amend`

**Comment by abhsag24** [comment]
this is a very good tutorial which helped me out a lot: https://www.atlassian.com/git/tutorials/rewriting-history/

**Comment by hackrush01** [comment]
I'll change the commit message. But still this rebasing thing seems complex.

**Comment by abhsag24** [comment]
@hackrush01 i can't merged until your branch is rebased :(

**Pull request closed without merging**
