### PR TITLE
Limited CPU usage to roughly 2% (Issue #128)

### PR DESCRIPTION
**Pull request by Aniq55**
Limits CPU usage

### CODE REVIEW

**Comment by Aniq55** [comment]
@abhsag24 I dont understand

**Comment by abhsag24** [comment]
@Aniq55? Why did u close the PR?

**Comment by Aniq55** [comment]
I clicked on close and comment by mistake

**Comment by abhsag24** [comment]
@Aniq55 which comment did you not understand?

**Comment by Aniq55** [comment]
@abhsag24  the one about the utils.py

**Comment by abhsag24** [comment]
@Aniq55 ohh yes I meant create a new utils.py :P I'm reviewing on phone sorry if I don't make a lot of sense :P

**Comment by Aniq55** [comment]
@abhsag24 But I've made change in a loop of scheduler.py

**Comment by abhsag24** [comment]
@Aniq55 we do not want merge commits can u remove that?

**Comment by Aniq55** [comment]
Oh! You want a separate file? I dont know. I'll work it out later then.

**Comment by Aniq55** [comment]
@abhsag24 But it is working quite awesome, I just checked the CPU time is reduced to 0.3% at times

**Comment by Aniq55** [comment]
are you referring to commit:	e5d8f8c

**Comment by nkprince007** [comment]
Hey, you're gonna close PR's unknowingly, if you update your ref heads on master and force push the changes... Don't do that.. creating PR's from other branches is advisable.

**Comment by Aniq55** [comment]
okay. Sorry for this.

**Pull request closed without merging**
