### PR TITLE
UIP.py: added exit message

### PR DESCRIPTION
**Pull request by trump16**
it will left an exit message on user intrupt

### CODE REVIEW

**Comment by nkprince007** [comment]
Please follow the contribution notes and run coala-ci before you make commits

**Comment by nkprince007** [comment]
Linting issues won't be tolerated @trump16

**Comment by abhsag24** [comment]
@trump16 alsowe just need that last commit, rebase away the other two

**Comment by trump16** [comment]
ok i will rebase the other two.. @abhsag24

**Comment by Aniq55** [comment]
@trump16 please check if there is any indentation error. I'm not sure that it is the problem, but it might be.

**Comment by abhsag24** [comment]
@trump16 you need to run `coala` before submitting a patch, also you need to solve mrege conflicts now :P

**Comment by DarkSouL11** [comment]
@abhsag24  PR looks good. Check it once and merge :)

**Pull request merged**
