### PR TITLE
Flush Button Removed, Issue #350

### PR DESCRIPTION
**Pull request by kaushalvivek**
The flush button has been removed from generalTab.py.

### CODE REVIEW

**Comment by abhsag24** [comment]
Hi thank you for your Patch make sure you have the right commit structure that is 
```
tag: Shortlog

body
Fixes <issue number/url>
```
Also please upload a screenshot if you have made changes to the gui.

**Comment by abhsag24** [comment]
@kaushalvivek can u please squash all your commits into one commit?

**Comment by abhsag24** [comment]
also you have linting issues. Please correct those.

**Comment by abhsag24** [comment]
if you need any help. Please reach us here: https://gitter.im/NIT-dgp/General

**Comment by nkprince007** [comment]
Closing due to inactivity.

**Pull request closed without merging**
