### PR TITLE
WIP: Make it possible to setup in virtualenv

### PR DESCRIPTION
**Pull request by ghoshbishakh**
Using a virtualenv gtk is not found. Any idea how to fix that?

### CODE REVIEW

**Comment by abhsag24** [comment]
@rultor merge

**Comment by abhsag24** [comment]
ahh i guess i need to configure rultor, i'll cherry-pick your commit and merge it myself till i can configure rultor :D

**Comment by abhsag24** [comment]
ohh sorry didnt see it was WIP :P

**Comment by ghoshbishakh** [comment]
@abhsag24 so any idea if it is possible to make it work in a virtualenv atall?

**Comment by abhsag24** [comment]
I thought you marked the PR wip because u wanted to add more commits, the
gitignore should do fine, just merge

**Comment by ghoshbishakh** [comment]
@abhsag24 no no it is giving me some issues with gtk or something.

**Comment by abhsag24** [comment]
Could you open an issue with the traceback you get, I'll investigate
tomorrow morning

**Comment by abhsag24** [comment]
@ghoshbishakh  still waiting for the issue? you want me to merge this PR? its mergeable

**Comment by ghoshbishakh** [comment]
No do not merge it. Ill post the traceback here

**Comment by abhsag24** [comment]
I urge you to open an issue please.

**Comment by abhsag24** [comment]
@ghoshbishak closing this as we discussed python3-gobject needs to be built from source inside `venv`. Which is infeasible.

**Pull request closed without merging**
