### PR TITLE
UIP.py: Modified the welcome message.

### LINKED ISSUE #102: Add "Press ctrl-c to exit" on welcome message

### PR DESCRIPTION
**Pull request by hassi2016**
Fixes #102

### CODE REVIEW

**Comment by hassi2016** [comment]
Kk will make in single print.

**Comment by nkprince007** [comment]
Could you please reword the commit message to something more practical,
like `Modified welcome message`.

**Comment by hassi2016** [comment]
Have modified the commit message and added a body too .

**Comment by DarkSouL11** [comment]
@hassi2016 please check the file you have modified you haven't cleared the conflict.

**Pull request merged**
