### PR TITLE
Setup tool requirement

### LINKED ISSUE #183: add setuptools required in readme
in the setup section for developers add: ```Make sure you have setuptools, to do that  run `pip install setuptools` ```

### PR DESCRIPTION
**Pull request by ssg2526**
readme.md: the package setup tools is required

fixes #183

### CODE REVIEW

**Comment by nemaniarjun** [comment]
Please use the text in the original issue. We also need to tell how to install setuptools.

**Comment by nkprince007** [comment]
@ssg2526 Leave the previous commit shortlog as is, just change the body of the message.
It's gonna be a lot cumbersome, and commit heading length should be limited to 50 chars

**Comment by ssg2526** [comment]
i am new to git because of that i am facing some problems so i am closing this PR and i will make a new one with a cleaner commit history

**Comment by nkprince007** [comment]
No, it isn't an issue @ssg2526, You could do whatever changes you need on your local repo and force push them onto the same PR to reflect the changes here. Get used to it. You don't need to close PR's. It isn't the right thing to do, even as a beginner.

**Comment by nkprince007** [comment]
Join our gitter chatroom to get started. Link goes [here](https://gitter.im/NIT-dgp/General)

**Pull request closed without merging**
