### PR TITLE
scheduler: Correct schedule Thread use

### PR DESCRIPTION
**Pull request by abhsag24**
Fixes https://github.com/NIT-dgp/UIP/issues/351
CC @SACHIN-13  @nkprince007

### CODE REVIEW

**Comment by abhsag24** [comment]
Hi thank you for your Patch make sure you have the right commit structure that is 
```
tag: Shortlog

body
Fixes <issue number/url>
```
Also please upload a screenshot if you have made changes to the gui.

**Comment by SACHIN-13** [comment]
the code exits if UIP command is run, without any images being downloaded!
probably because both the threads here are daemon threads so the main thread doesn't wait for them to finish and it itself stops. if we add an infinite loop after creating the scheduler thread in UIP.py, it solves the problem!

**Comment by abhsag24** [comment]
ahh yes, i see.

**Comment by abhsag24** [comment]
i'll try and make it work for both

**Comment by nemaniarjun** [comment]
Looks good. :+1:

**Pull request merged**
